### ISSUE TITLE
Unreachable URLs

### ISSUE THREAD

**Issue by ellacharmed** [DataTalksClub/course-management-platform#53]
Not sure if intentional or a mistake (that happens for each homework appears kinda dubious), but some URLs are not even a valid page (404'd) or not reachable due to wrong links or have symbols.

**Comment by ellacharmed** [comment]
Oh, this occurs in the homework link as well, so not sure if you want to have them in one issue#id?

- learning in public (eg: https://%20the%20(above)%20link%20is%20embedded%20in%20my%20personal%20website%20(below)/)

- homeworks link to parent folder or parent blog page or a profile page, not to a worked solution page.  
- homework linked to a previous homework's solution (eg: https://courses.datatalks.club/mlops-zoomcamp-2024/leaderboard/2379/)
Maybe should check for extensions for *.ipynb, *.md, *.py, *.html? Or make it a requirement for folder that has solution to be homework-## where the ## matches the homework number? As there are instances where we have multiple files to get to the solution, like scripts, docker stuff, etc

**Comment by alex-kolmakov** [comment]
Hopefully [this pull request](url) will help a bit.

**Comment by alexeygrigorev** [comment]
yes that PR solves it. Thanks Alex!
