### ISSUE TITLE
Changing the "Problems or Comments" to "Improvements or Comments"

### ISSUE THREAD

**Issue by MekongDelta-mind** [DataTalksClub/course-management-platform#57]
Problems or Comments would make the learner a bit defensive and wouldn't even care to even go through the comments or improvements. These are comments which the reviewers take time out of their busy schedule and invest to help learners better their project.

If we could change it from " `Problems` or Comments " to "`improvements` or Comments ", it would sound better and the learners would be more receptive of the suggestions( I hope ). And once the review is done, if the learners pass, I don't think they even care about the "Problems or Comments section". By this change they would at least read and if motivated enough would implement the changes.

**Comment by alexeygrigorev** [comment]
![image](https://github.com/user-attachments/assets/a556e2ad-05a5-4407-a8ca-41e9e16a929b)

Will be included in the next release. Thanks for the suggestion!
