### ISSUE TITLE
Unfold admin integration for awesome admin UI and other features

### ISSUE THREAD

**Issue by M97Chahboun** [DataTalksClub/course-management-platform#6]
I start working on it but before continue on implementation I need your opinion
![Screenshot 2024-02-10 at 14 54 28](https://github.com/DataTalksClub/course-management-platform/assets/69054810/438a6d02-3b44-4778-a067-13e59fd6123f)

[Unfold admin website](https://www.unfoldadmin.com)

**Comment by M97Chahboun** [comment]
![Screenshot 2024-02-10 at 14 57 42](https://github.com/DataTalksClub/course-management-platform/assets/69054810/e757e96b-fb3e-4f30-afab-a24de0710026)

**Comment by alexeygrigorev** [comment]
Looks really nice! Thanks!
