### ISSUE TITLE
wrong reference page for the homework markdown page in the Data Ingestion submission form

### ISSUE THREAD

**Issue by lucapug** [DataTalksClub/course-management-platform#7]
Seems there is a wrong link (to the datawarehouse homework md page) in the [submission form for workshop 1 Data Ingestion](https://courses.datatalks.club/de-zoomcamp-2024/homework/workshop1) (in the header part just above the deadline datetime).
The correct page to reference for the homework is [this one](https://github.com/lucapug/data-engineering-zoomcamp/blob/main/cohorts/2024/workshops/dlt_resources/homework_starter.ipynb)

**Comment by alexeygrigorev** [comment]
Thank you!
